### PR TITLE
Fixed crash on DepthCloudPlugin

### PR DESCRIPTION
**Pull request by ahcorde**
Related with this issue https://github.com/ros2/rviz/issues/1132

### CODE REVIEW

**Comment by clalancette** [comment]
Does this same bug occur with `rolling`?

**Comment by ahcorde** [comment]
> Does this same bug occur with `rolling`?

Yes, should I retarget this to rolling and then backport, isn't it ?

**Comment by clalancette** [comment]
> Yes, should I retarget this to rolling and then backport, isn't it ?

Yeah, that is the usual practice on the ROS 2 repositories.

**Comment by ahcorde** [comment]
@clalancette retargeted to `rolling`

**Comment by ahcorde** [comment]
friendly ping @clalancette

**Comment by ahcorde** [comment]
friendly ping @clalancette

**Review by adityapande-1995 — APPROVED** [review]

**Comment by adityapande-1995** [comment]
Looks good with green CI !

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20352/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14760/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21103/)

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble iron

**Pull request merged**
