### PR TITLE
terrible hack to suppress cmake warning

### LINKED ISSUE #524: rviz_assimp_vendor CMake CMP0012 build error
CMake 3.16.3 on Ubuntu Focal, building from Master

```
--- stderr: rviz_assimp_vendor                                                            
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimpTargets.cmake:54 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  CMakeLists.txt:55 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

---
```

Originally (mis)filed as https://github.com/ros-visualization/rviz/issues/1479

### PR DESCRIPTION
**Pull request by wjwwood**
Fixes https://github.com/ros2/rviz/issues/524

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM pending CI

**Comment by wjwwood** [comment]
CI before this change:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10579/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6028/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8615/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10476/)

CI after this change:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10583/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6031/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8619/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10480/)

CI on Linux up to `rviz2` (build and test) only Fast-RTPS:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/10594/)

**Comment by jacobperron** [comment]
The CI up to `rviz2` doesn't appear to be testing the branch with the patch.

**Comment by wjwwood** [comment]
Oops my mistake started a new job.

**Comment by wjwwood** [comment]
Update on this one, because we find_package assimp in a few places, I need a better patch. I've been working on it, but I'm not done yet.

**Comment by wjwwood** [comment]
CI after improving the hacks:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/10615/) (test failure is flake8 in `resource_retriever`, unrelated)

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
