### PR TITLE
Migrate pose array display

### LINKED ISSUE #85: Migrate PoseArrayDisplay

### PR DESCRIPTION
**Pull request by botteroa-si**
Closes #85 

This pull request includes:
- migrate Pose Array Display;
- refactor PoseArrayDisplay class;
- enable alpha blending for flat arrows;
- add tests.

### CODE REVIEW

**Comment by botteroa-si** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4099/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1189/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3394/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4203/)

**Comment by botteroa-si** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4100/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1190/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3395/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4204/)

**Comment by anhosi** [comment]
@wjwwood These CI failures seem unrelated to rviz.

**Comment by mikaelarguedas** [comment]
> These CI failures seem unrelated to rviz.

:+1: Yeah it looks like something broke in flake8, we see the same failures on master

**Review by wjwwood — APPROVED** [review]
lgtm

**Pull request merged**
