### PR TITLE
Fix implicit capture of "this" warning in C++20

### PR DESCRIPTION
**Pull request by AiVerisimilitude**

### CODE REVIEW

**Comment by clalancette** [comment]
The change itself makes sense to me, but please fix up the style (remove the spaces around `this`) so that the linters are happy.

**Comment by AiVerisimilitude** [comment]
> The change itself makes sense to me, but please fix up the style (remove the spaces around `this`) so that the linters are happy.

Sorry, was convinced I had run those locally already. Thanks for the review!

**Review by clalancette — APPROVED** [review]
Looks good to me.  I'll also run our more full CI on this change.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19430/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13954/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20153/)

**Pull request merged**
