### PR TITLE
[Foxy] Expose VisualizationManager and YamlConfigReader to the public API

### PR DESCRIPTION
**Pull request by mjeronimo**
(Backport of https://github.com/ros2/rviz/pull/649 to Foxy, requested here: https://github.com/ros2/rviz/issues/664)

In order to create a standalone Qt application that contains an embedded RViz2 RenderPanel,
the header for the VisualizationManager class must be moved to the public API to allow
instantiating a VisualizationManager independently from the context of the RViz2 application.
The YamlConfigReader class also needs to be moved to the public API to allow runtime
configuration of the VisualizationManager, for example to add a Grid plugin.

Signed-off-by: Joe Schornak <joe.schornak@gmail.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Doesn't change API (other than exposing some functions that weren't there before), so it seems fine to me with green CI.

**Comment by mjeronimo** [comment]
@clalancette Although it doesn't change API or ABI, it would change the location of the headers, which would impact current Foxy code, correct? The code would no longer compile without updating the source. I wasn't sure about that aspect.

**Comment by clalancette** [comment]
> @clalancette Although it doesn't change API or ABI, it would change the location of the headers, which would impact current Foxy code, correct? The code would no longer compile without updating the source. I wasn't sure about that aspect.

As far as I understand, you are taking an internal header (which wasn't installed), and now making it external.  Anything compiling against Foxy wouldn't have a problem, because they never had access to the original header to begin with.  Does that address your concern, or do you mean something else?

The other aspect of this is that a third-party might start to take advantage of that header, and it wouldn't be available until "later" versions of the Foxy packages where this PR was integrated.  But I still think that is fine; any package that will be depending on this couldn't be released until the Foxy update with this code was released.

**Comment by clalancette** [comment]
(all of that said, we should probably get another opinion from @jacobperron before merging)

**Review by jacobperron — APPROVED** [review]
Seems okay to me.

**Comment by mjeronimo** [comment]
@clalancette Right,  not a concern after all since it was an internal header that would now be exposed; there wouldn't be any existing client code that would have used it. Thanks for the input.

**Comment by mjeronimo** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14778/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9527/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12444/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14925/)

**Comment by mjeronimo** [comment]
Windows has unrelated cmake warnings. Merging.

**Pull request merged**
