### PR TITLE
[foxy-backport] fast forward of ros2 (default) to foxy

### PR DESCRIPTION
**Pull request by wjwwood**
I went over the pull requests merged since the foxy release, and I believe all of them are ok from an ABI perspective. There were some build system changes, but I believe they should be backwards compatible, but I'm not 100% sure of that.

I'll for feedback on that point for some of the individual commits, but here is a list of all of them:

- restore compatibility with older Qt versions (#561)
- Suppress warnings when building with older Qt versions. (#562)
- Don't try to moc generate env_config.hpp file. (#550)
-  rewrite hack to avoid CMake warning with assimp 5.0.1 and older, apply cross platform (#565)
- Use dedicated TransformListener thread (#551)
- restore alphabetical include order (#567)
  - @Karsten1987 this one was not added to the back port project, should it be? (seems ok to me)
- Don't install test header files in rviz_rendering. (#564)
  - @clalancette should this one be back ported? It was not on the back port project
  - it seems like the most risky of the group, but it also (after reading it again) seems safe, as we never intended people to use the test headers which had been installed

@jacobperron FYI

### CODE REVIEW

**Review by Karsten1987 — COMMENTED** [review]
I'll give thumbs up for my commits at least. But just for my understanding: 
https://github.com/ros2/rviz/pull/567 should be closed in favor of this PR then, right? Also, I thought it was on the project board. But maybe I missed something here.

**Comment by wjwwood** [comment]
Sorry, I didn't see that. Yeah I will close #567 in favor of this one if all of the commits are ok.

I think it's helpful for the original issue/pull request to be in the "needs backport" column until it is released into foxy. But that's just my take.

**Comment by clalancette** [comment]
> Don't install test header files in rviz_rendering. (#564)
> 
>     * @clalancette should this one be back ported? It was not on the back port project
> 
>     * it seems like the most risky of the group, but it also (after reading it again) seems safe, as we never intended people to use the test headers which had been installed

I'm on the fence about it.  It should be relatively harmless, but as you say, it is the riskiest of the group.  If you think that the benefit of being able to cherry-pick commits between `ros2` and `foxy` outweigh the (pretty small) potential for regression, I'd say go for it.  I mostly didn't put it on the backport project since I am very conservative about backporting.

**Comment by wjwwood** [comment]
Ok, @jacobperron do you have an opinion?

**Review by jacobperron — APPROVED** [review]
A fast-forward is okay by me.

The potential for a regression due to #564 seems relatively low considering it is touching test files.

**Comment by wjwwood** [comment]
Ok, I'll do the fast-forward then.

**Comment by wjwwood** [comment]
Because there's a header that was moved to public from private and therefore adds API:

https://github.com/ros2/rviz/pull/564/files#diff-608c586d26f0d375668eb4e5e1e4acfc

I think I'll do a minor version bump.

**Pull request merged**
