### PR TITLE
Switch to ament_cmake_vendor_package

### PR DESCRIPTION
**Pull request by cottsay**
Part of https://github.com/ament/ament_cmake/pull/429

This is the biggest of the vendoring changes. I find it easier to ignore the diffs and just inspect the before/after.

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/18975/)
* Linux [Build Status](https://ci.ros2.org/job/ci_linux/18976/) (FORCE_BUILD_VENDOR_PKG)
* Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/13502/)
* Linux-rhel [Build Status](https://ci.ros2.org/job/ci_linux-rhel/431/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/19721/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/19722/)

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Comment by cottsay** [comment]
This is blocked on a release of `ignition_math6_vendor`.

**Comment by cottsay** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
Just as an FYI, this seems to have broken the clang_libcxx build: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1558/ .  It's not important enough to revert, but I would appreciate a quick look to see if it is an easy fix.

**Pull request merged**
