### PR TITLE
Solve compiler warning in Focal

### PR DESCRIPTION
**Pull request by ivanpauno**
### Description

Fixes warning in Focal: https://ci.ros2.org/job/ci_linux/9175/warnings23Result/package.-1204707637/

### Checklist

- [ ] If you are addressing rendering issues, please provide:
  - [ ] Images of both, broken and fixed renderings.
  - [ ] Source code to reproduce the issue, e.g. a `YAML` or `rosbag` file with a `MarkerArray` msg.
- [ ] If you are changing GUI, please include screenshots showing how things looked *before* and *after*.
- [ ] Choose the proper target branch: latest release branch, for non-ABI-breaking changes, *future* release branch otherwise.
      Due to the lack of active maintainers, we cannot provide support for older release branches anymore.
- [ ] Did you change how RViz works? Added new functionality? Do not forget to update the tutorials and/or documentation on the [ROS wiki](http://wiki.ros.org/rviz)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-visualization/rviz/pulls) to support the maintainers of RViz. Refer to the [RViz Wiki](https://github.com/ros-visualization/rviz/wiki/Maintainer-Guide#reviewing-pull-requests) for reviewing guidelines.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM with green CI

**Comment by ivanpauno** [comment]
@jacobperron Should I send the patch to https://github.com/ros-visualization/rviz, and later this repos is rebased/the commit cherry-picked? Should I send a fix to both? I'm not sure how this is managed.

**Comment by jacobperron** [comment]
https://github.com/ros-visualization/rviz and this repository have diverged significantly. My understanding is that this version has undergone a re-design since ROS 2. So, I don't think all patches apply to both repositories. If a particular patch can be made to both, then I suggest making PRs independently. @wjwwood can correct me if I'm wrong.

I've triggered CI for this patch:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9233/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4922/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7539/) (same failures on nightly)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9153/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/35/)

**Comment by wjwwood** [comment]
That sounds right.

**Pull request merged**
