### PR TITLE
Humble namespace in title

### PR DESCRIPTION
**Pull request by maxbader**
Hi

I like to request a merge, with the proposed changes RVIZ shows the currently used namespace in the title. This comes very handy when using multiple robots with namespaces.

### CODE REVIEW

**Comment by maxbader** [comment]
Details how it looks can be seen at [robotics.stackexchange.com](https://robotics.stackexchange.com/questions/104534/is-it-possible-to-change-the-rviz2-window-title-or-to-show-the-namespace-used)

**Review by clalancette — CHANGES_REQUESTED** [review]
I'm OK with this as a feature, but as an *optional* feature.  In particular, I think if you have a long namespace, *and* you are using a custom config file, the title will be unreadable.

Therefore, what I think we should do here is add the ability for the user to set a custom title instead, and then save that into the config file.  Then it can be whatever you want.

**Comment by maxbader** [comment]
@clalancette
I also thought about a parameter, but I would set the namespace display as default. A bigger problem than long namespaces are long filenames. Here the question arises whether the display of the whole path is necessary.

**Comment by clalancette** [comment]
> A bigger problem than long namespaces are long filenames. Here the question arises whether the display of the whole path is necessary.

That's a good point, I agree that this is a problem.

This actually suggests a solution to both of these, which is to add the ability for users to specify a custom title, with replacement tokens.  That is, the user could set something like:

```
customTitle: My RViz {filename} - {namespace}
```

And we would replace `{filename}` and `{namespace}` with the appropriate information.  What we should by default we could still discuss, but I actually think it should probably be only `RViz`.

**Comment by clalancette** [comment]
(regardless, any of these changes should target the `rolling` branch first, and then we can consider backporting to `humble`)

**Comment by maxbader** [comment]
I also have a branch for rolling ready.
[rolling_namespace_in_title](https://github.com/tuw-robotics/rviz/tree/rolling_namespace_in_title)

**Comment by maxbader** [comment]
It's ready, now you can start rviz with the option -t like `ros2 run rviz2 rviz2 -d ./ws01/src/stage_ros2/config/rviz/robot_ns.rviz __ns:=/robot_0 -t "NAMESPACE - FILE - RViz2" --ros-args  -r /tf:=tf -r /tf_static:=tf_static`

* NAMESPACE is replaced by the namespace used
* PATH directory to the config file
* FILE config file name

**Comment by ahcorde** [comment]
Replaced by https://github.com/ros2/rviz/pull/1099

**Pull request closed without merging**
