### PR TITLE
[foxy] Fix support for assimp 5.1.0 (#817)

### PR DESCRIPTION
**Pull request by Ace314159**
@clalancette I tried backporting #817 to foxy. I don't think this will cause any issues since I haven't removed any exports.

### CODE REVIEW

**Comment by jacobperron** [comment]
If we backport this to Foxy, I think we should also backport it to the newer Galactic.

**Comment by jacobperron** [comment]
Is there a reason you did not include the changes to rviz_common from #817?

**Comment by Ace314159** [comment]
I didn't include the change to `rviz_common` since if any downstream package expects `rviz_assimp_vendor` to be exported by it, changing that might break their build. Even though `rviz_common` shouldn't export `rviz_assimp_vendor`, they may still rely on this behavior. I think this was what @clalancette was also hinting at in https://github.com/ros2/rviz/pull/817#issuecomment-1021200497

I'm not sure if such a case exists or if we should care about that, so I chose to be safe and not include those changes. I can add them if you want.

**Comment by jacobperron** [comment]
Makes sense to me, thanks for clarifying. 

I'm okay with backporting this to Foxy and Galactic if @clalancette is okay with it.

**Comment by clalancette** [comment]
This is a reasonable backport to me, assuming that CI is green.

**Review by jacobperron — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16201/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10828/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16558/)

**Pull request merged**
