### PR TITLE
Fix missing "X" icon in panel close button

### LINKED ISSUE #327: Closing window "X" missing on Windows
On Windows, the "X" for closing windows (see e.g. the displays panel) is missing. 
Instead, I only see a grey button with no content. 

This seems to be a problem with Qt or how rviz uses Qt windows.

### LINKED ISSUE #692: Panel close button is missing "X" icon
The upper right-hand corner of every panel in RViz2 has a close button in order to close the panel.  On both Rolling and Galactic, that button exists, but is blank.  That button should have an "X" icon to indicate to the user that this is where it should be closed.

### PR DESCRIPTION
**Pull request by rebecca-butler**
Closes #327, #692

We're currently using `QIcon::fromTheme()` to load the `window-close` icon. This uses the GNOME theme by default and is only supported on X11 , so it won't show up on Windows or macOS. 

I think we should instead add the `window-close` icon as a png resource and load it using `rviz_common::loadPixmap()`. This will work on all platforms, and it's also consistent with how we load other icons in RViz.

Signed-off-by: Rebecca Butler <rebecca@openrobotics.org>

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
cpplint is failing 

```
https://build.ros2.org/job/Rpr__rviz__ubuntu_focal_amd64/175/testReport/junit/(root)/projectroot/cpplint/
```

**Comment by rebecca-butler** [comment]
CI build: `--packages-up-to rviz_common`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14913/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9655/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12584/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15071/)

**Review by ahcorde — APPROVED** [review]

**Comment by jacobperron** [comment]
Where was the icon sourced? We should be aware of any license associated with it since we'll be redistributing it with RViz.

**Comment by rebecca-butler** [comment]
That's a good point. The icon is part of the [Yaru desktop theme](https://github.com/ubuntu/yaru), and according to the README it's licensed under Creative Commons Attribution-ShareAlike 4.0. We should be attributing it if we're going to use it.

I did a bit of digging into this because I was curious where the other RViz icons come from. Most of them are from the Tango desktop theme, which is in the [public domain](https://en.wikipedia.org/wiki/Tango_Desktop_Project). 

The Tango close icon is actually already in this repo under the name `failed_display.png`, so we could just reuse that icon for the window close button. Then we can avoid licensing issues.

**Comment by rebecca-butler** [comment]
Anyway, I now know more about icon themes and licenses then I ever wanted to know.

**Comment by clalancette** [comment]
> The Tango close icon is actually already in this repo under the name `failed_display.png`, so we could just reuse that icon for the window close button. Then we can avoid licensing issues.

Yeah, I think we should do this.  The licensing issue is the most important reason, but it is also easier to just say "all of our icons come from Tango".

**Comment by rebecca-butler** [comment]
> Yeah, I think we should do this.

Done in a follow-up PR: #734

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-9-16/22372/1

**Pull request merged**
