### PR TITLE
Remove the rviz subdirectory from the rviz2 repository.

### PR DESCRIPTION
**Pull request by clalancette**
It feels like we are never going to merge this back with
the original rviz repository, nor merge the rviz and rviz2
subdirectories.  Therefore this commit removes effectively
dead code from the rviz2 repository.

Consider this an request for comments.  If we end up doing this, I'll also suggest that we "break the link" between https://github.com/ros-visualization/rviz and this repository, as they are not really related anymore.

### CODE REVIEW

**Comment by wjwwood** [comment]
> It feels like we are never going to merge this back with
the original rviz repository, nor merge the rviz and rviz2
subdirectories

That's not the purpose of the rviz directory here. The idea was that you moved things from the rviz directory as you ported them. Just deleting it without looking at what's still there and why is maybe a bad idea...

**Comment by wjwwood** [comment]
> I'll also suggest that we "break the link" between https://github.com/ros-visualization/rviz and this repository, as they are not really related anymore.

I think "unrelated" isn't accurate, but I agree it no longer needs to be a fork. We should update the README to redirect users to the ROS 1 rviz repository in case they get confused, if you do make it not a fork.

**Comment by clalancette** [comment]
> That's not the purpose of the rviz directory here. The idea was that you moved things from the rviz directory as you ported them. Just deleting it without looking at what's still there and why is maybe a bad idea...

Taking a quick look at what is in the `rviz` directory:
* cmake stuff - this is totally different now, so we can remove this
* doc - There is some overview documentation which would probably be good to have eventually; we can probably just move this documentation to the `rviz2` directory instead with a little cleanup
* scripts - probably can remove them
* src/image_view - standalone image_viewer, not sure it belongs here, I would remove it
* src/python_bindings - I guess python bindings for rviz?  Not sure
* src/rviz/default_plugin - Looks like there are 2 plugins not yet ported: DepthCloudDisplay and EffortDisplay

With all of that said, my suggestion is to move the doc directory out, and still remove the rest.  If someone is going to come along and port the DepthCloudDisplay and EffortDisplay, its just as easy for them to look at the original code in the `rviz` repository as it is for them to look at it here.  The same goes for the python bindings; I'm guessing if we reintroduced them they would take a very different form.

That all being said, I won't push on this too hard.  I don't like carrying dead code around, but if you think this is still useful here I'll just close this PR.

**Comment by wjwwood** [comment]
Ok, well I think that good enough of a check to justify removing it, though I don't know where you'd move the doc folder so that it's preserved but not mistaken for active docs, I guess a new folder like "not_yet_migrated_from_ros1" or something like that.

The thing I was most worried about was actual plugins, but since most have moved, I guess we can remove them now.

**Comment by clalancette** [comment]
Thanks for merging #600.  With that, I've now rebased and force-pushed this branch.  I think we are good to review here.

**Review by wjwwood — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks for the approval.  Given that this is removing a currently-ignored directory, I'm not going to run CI on it.  I'll just wait for the PR job to come back green, then go ahead and merge.

**Pull request merged**
