### PR TITLE
add implementation for cancel interface

### LINKED ISSUE #703: rviz2 randomly crashes while running with nav2 stack
### Basic info
RViz2 from frequently crashes during the use while running with Nav2 stack. The problem appears in random places even if all Nav2-related stuff was disabled (see minimal configuration file in reproduction section below). Crashes were [noted](https://github.com/ros-planning/navigation2/issues/2367) on Crystal and still appearing on latest Rolling.

### More info
Crashes appears irregularly in different places. All types of messages and backtraces were detected and sorted-out by their probability of occurrence:
1. Invalid Argument
```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
```
2. Segfault
```
Thread 16 "rviz2" received signal SIGSEGV, Segmentation fault.
```
3. Assertion Robust
```
rviz2: ../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
--Type <RET> for more, q to quit, c to continue without paging--
```
4. Deadlock: RViz2 hangs during the use
5. Assertion Prio
```
[rviz2-4] rviz2: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
[ERROR] [rviz2-4]: process has died [pid 174985, exit code -6, cmd '/home/leha/ros2_rolling/install/rviz2/lib/rviz2/rviz2 -d /home/leha/nav2_ws/install/nav2_bringup/share/nav2_bringup/rviz/nav2_default_view.rviz --ros-args'].
```

For the types No.1-4 GDB backtraces were collected and attached in the archive: [backtraces.zip](https://github.com/ros2/rviz/files/6618073/backtraces.zip)
For type No.5 backtrace was not obtained (it was detected once). All of the problems above were detected by using the same scenario. Thus maybe (but not proven) all issue types have the same root cause.

### Steps to reproduce

Despite the problem is irregular and there is no 100% algorithm how to reproduce it, here are the steps allowing with more or less probability to get the problem:
1. Replace `navigation2/nav2_bringup/bringup/rviz/nav2_default_view.rviz` file with minimal repro-configuraiton attached to current issue: [nav2_default_view.rviz.zip](https://github.com/ros2/rviz/files/6618076/nav2_default_view.rviz.zip)
2. Run Nav2 simulation as usual:
```
ros2 launch nav2_bringup tb3_simulation_launch.py
```
3. In appeared RViz screen set robot pose by "2D Pose Estimate"
4. enable-disable many times the "Controller" checkbox as shown in the picture below:
reproduction
5. If problem won't appear within ~30-40 seconds, close RViz and repeat starting from step No.2.

### Environment
* Ubuntu 20.04 x64
* ROS2 Distro: Rolling built from sources (`ros2.repos` from Jun 1st).
* Nav2 main and Nav2 dependencies were [built from sources](https://navigation.ros.org/build_instructions/index.html#manually-build-main). Nav2 commit: https://github.com/ros-planning/navigation2/commit/b63b11f8a638faf389d6b99911d95899abe1580b
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
RViz commit: 94f6dd6958b2927a307893ff174f182dcc7afd0e
```
$ ros2 run rviz2 rviz2 -l
...
[INFO] [1623165832.507667729] [rviz2]: *-*-* OGRE Initialising
[INFO] [1623165832.507680536] [rviz2]: *-*-* Version 1.12.1 (Rhagorthua)
...
[INFO] [1623166434.886964038] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
```

Qt version is not printed by rviz:
```
$ qmake --version
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```
* If source build, which git commit?
The problem is long-standing detected since Crystal. Accused commit was not found.

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rviz/issues/703

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Comment by iuhilnehc-ynos** [comment]
This PR is based on https://github.com/ros2/geometry2/pull/490

**Review by clalancette — COMMENTED** [review]
So I see that `TFFrameTransformer::cancel` calls `TFWrapper::cancel`, which then calls into `tf2_ros::Buffer::cancel`.

But what calls `TFFrameTransform::cancel` to begin with?

**Comment by iuhilnehc-ynos** [comment]
@clalancette 



> But what calls `TFFrameTransform::cancel` to begin with?

the `cancel` could also be called from destructor `MessageFilter<>::~MessageFilter()`, please refer to the following backtrace.

<details><summary> backtrace </summary>
<p>

```cpp
(gdb) bt
#0  rviz_default_plugins::transformation::TFFrameTransformer::cancel(tf2_ros::TransformStampedFuture const&) (this=0x55555698ad80, ts_future=...)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rviz/rviz_default_plugins/src/rviz_default_plugins/transformation/tf_frame_transformer.cpp:210
#1  0x00007ffedf42e110 in tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>::clear() (this=0x555556aac460) at /home/chenlh/Projects/ROS2/ros2-master/install/include/tf2_ros/message_filter.h:342
#2  0x00007ffedf439cad in tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>::~MessageFilter() (this=0x555556aac460, __in_chrg=<optimized out>)
    at /home/chenlh/Projects/ROS2/ros2-master/install/include/tf2_ros/message_filter.h:273
#3  0x00007ffedf4665bf in __gnu_cxx::new_allocator<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> >::destroy<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> >(tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>*)
    (this=0x555556aac460, __p=0x555556aac460) at /usr/include/c++/9/ext/new_allocator.h:153
#4  0x00007ffedf45dc35 in std::allocator_traits<std::allocator<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> > >::destroy<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> >(std::allocator<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> >&, tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>*) (__a=..., __p=0x555556aac460) at /usr/include/c++/9/bits/alloc_traits.h:497
#5  0x00007ffedf45b747 in std::_Sp_counted_ptr_inplace<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>, std::allocator<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=0x555556aac450) at /usr/include/c++/9/bits/shared_ptr_base.h:557
#6  0x000055555555bea6 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x555556aac450)
    at /usr/include/c++/9/bits/shared_ptr_base.h:155
#7  0x000055555555b835 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=0x7fffffffab48, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:730
#8  0x00007ffedf42cee0 in std::__shared_ptr<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() (this=0x7fffffffab40, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#9  0x00007ffedf42df68 in std::__shared_ptr<tf2_ros::MessageFilter<geometry_msgs::msg::PolygonStamped_<std::allocator<void> >, rviz_common::transformation::FrameTransformer>, (__gnu_cxx::_Lock_policy)2>::reset() (this=0x555556a91d60) at /usr/include/c++/9/bits/shared_ptr_base.h:1287
#10 0x00007ffedf42d66c in rviz_common::MessageFilterDisplay<geometry_msgs::msg::PolygonStamped_<std::allocator<void> > >::unsubscribe() (this=
    0x555556a91c30) at /home/chenlh/Projects/ROS2/ros2-master/install/include/rviz_common/message_filter_display.hpp:166
#11 0x00007ffedf42ca49 in rviz_common::MessageFilterDisplay<geometry_msgs::msg::PolygonStamped_<std::allocator<void> > >::onDisable()
    (this=0x555556a91c30) at /home/chenlh/Projects/ROS2/ros2-master/install/include/rviz_common/message_filter_display.hpp:177
#12 0x00007ffff7e370b6 in rviz_common::Display::onEnableChanged() (this=0x555556a91c30)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rviz/rviz_common/src/rviz_common/display.cpp:352
#13 0x00007ffff7e325e5 in rviz_common::DisplayGroup::onEnableChanged() (this=0x5555569ebca0)
    at /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rviz/rviz_common/src/rviz_common/display_group.cpp:138
#14 0x00007ffff7dd26e2 in rviz_common::Display::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
<...>
```

</p>
</details>


NOTE:

- geometry2/tf2_ros/include/tf2_ros/message_filter.h

```cpp
template<class M, class BufferT = tf2_ros::Buffer>
class MessageFilter 
```

The second template param `BufferT` can be either `tf2_ros::Buffer` or `rviz_default_plugins::transformation::FrameTransformer`.

- rviz/rviz_common/src/rviz_common/transformation/transformation_manager.cpp

```cpp
rviz_common::transformation::TransformationManager::setTransformer
	to create rviz_default_plugins::transformation::TFFrameTransformer
	emit transformerChanged()
```

- rviz/rviz_common/include/rviz_common/message_filter_display.hpp

```cpp
MessageFilterDisplay::subscribe
  tf_filter_ =
    std::make_shared<tf2_ros::MessageFilter<MessageType, transformation::FrameTransformer>>(
    *context_->getFrameManager()->getTransformer(),
    fixed_frame_.toStdString(),
    static_cast<uint32_t>(message_queue_property_->getInt()),
    rviz_ros_node_.lock()->get_raw_node());

MessageFilterDisplay::unsubscribe
  tf_filter_.reset();
```

**Comment by iuhilnehc-ynos** [comment]
CI:
Build args: `--packages-above-and-dependencies tf2_ros rviz_common rviz_default_plugins`
Test args: `--packages-above tf2_ros rviz_common rviz_default_plugins`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15859/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10536/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13524/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16154/)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI for this is over in https://github.com/ros2/geometry2/pull/490

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-2022-02-17/24435/1

**Pull request merged**
