### PR TITLE
[backport Humble] load glb meshes

### PR DESCRIPTION
**Pull request by ahcorde**
Backported this PR https://github.com/ros2/rviz/pull/1001/files

Related with this issue https://github.com/RobotLocomotion/drake-ros/issues/335

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks like it does not break ABI or API, so looks good to me with green CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20382/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14791/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21131/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20383/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14792/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21132/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20385/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14795/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21135/)

**Comment by ahcorde** [comment]
can you take another look @clalancette ? Assimp version on Windows in different

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport iron

**Pull request merged**
