### PR TITLE
Migrate select tool

### LINKED ISSUE #211: Migrate Select tool
Migrate the Select tool to RViz for ROS2.

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Closes #211 

This PR migrates the select tool enabling selection. In addition, it adds tests and refactoring to the selection part of RViz. The major changes include:
- Split the SelectionManager into four parts: A HandlerManager to manage SelectionHandles, a SelectionManager to do selection, a ViewPicker to pick object (needed to focus without selection), which was previously hidden inside the SelectionManager but has little in common with it) and a SelectionRenderer encapsulating most Ogre functionality.
- Add tests to SelectionManager, HandlerManager and SelectionHandles. 
- Refactoring (and if necessary, unit testing) of all SelectionHandlers in `rviz_default_plugins`

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4287/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1292/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3520/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4367/)

**Comment by Martin-Idel-SI** [comment]
Try to fix error on Windows (we can't reproduce for whatever reason):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4297/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1298/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3527/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4376/)

The new CMake warning on Linux should be unrelated.

**Comment by anhosi** [comment]
New CI after we added some small refactorings:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4298/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1299/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3528/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4377/)

This windows test failure is not related to rviz.

**Comment by Martin-Idel-SI** [comment]
New CI after rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4338/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1321/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3558/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4408/)

**Review by wjwwood — APPROVED** [review]
lgtm

There were some files where the indentation of some statements looked weird, but it's not worth following up on in my opinion.

This was a large pr (whew 😅), so I tried to focus on files with a lot of back and forth deltas, and only skimmed files which were completely new or deleted.

**Pull request merged**
