### PR TITLE
Show link names in inertia error message

### LINKED ISSUE #872: Link inertia error should tell which link has inertia error
When displaying a robot model one might get the following error
`The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.`
which is coming from [here](https://github.com/ros2/rviz/blob/7b4ba855b5803ef8b77b7732889c8b1b6e43532b/rviz_default_plugins/src/rviz_default_plugins/robot/robot_link.cpp#L888-L890) 
Unfortunately, the name of the corresponding link is not given, so it is difficult to see which of the links is meant. For complex robot models, it is quiet cumbersome to search for this manually.
So I would propose to provide a message like this
`The link base_link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.`

### PR DESCRIPTION
**Pull request by timonegk**
Closes #872.

### CODE REVIEW

**Comment by timonegk** [comment]
Now the warning message is additionally suppressed for the base link and static links because it is common for them to not have an inertia, but it needs to be set in the urdf for some other programs, e.g. pybullet.

**Comment by clalancette** [comment]
@timonegk Can you please fix the linter warnings?  With that done, we can consider this for inclusion.

**Comment by timonegk** [comment]
@clalancette they are fixed

**Review by jacobperron — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17203/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11746/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17629/)

**Comment by clalancette** [comment]
The unstable Windows result has nothing to do with this PR, so I'll go ahead and merge.

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
