### PR TITLE
Don't treat warnings as errors when building Assimp

### PR DESCRIPTION
**Pull request by cottsay**
I'm seeing some build warnings (errors) on Fedora 39.

Under normal conditions, this code path isn't activated on Ubuntu, RHEL, or Windows. Here's an Ubuntu build with `FORCE_BUILD_VENDOR_PKG:BOOL=ON`:
[Build Status](https://ci.ros2.org/job/ci_linux/20557/)

### CODE REVIEW

**Comment by clalancette** [comment]
I'm all for the idea, but we are getting a CMake warning:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    ASSIMP_WARNINGS_AS_ERRORS
```

**Comment by cottsay** [comment]
Ugh, looks like this flag was introduced in 5.3.0. We need to update this to 5.3.1 to match noble anyway.

**Comment by cottsay** [comment]
After updating to 5.3.1, this should now work.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20906/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15208/)
* Linux-rhel [Build Status](https://ci.ros2.org/job/ci_linux-rhel/637/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21585/)

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Pull request merged**
