### PR TITLE
Add VisualizationManager and YamlConfigReader to the public API

### PR DESCRIPTION
**Pull request by schornakj**
In order to create a standalone Qt application that contains an embedded RViz2 RenderPanel, the header for the VisualizationManager class must be moved to the public API to allow instantiating a VisualizationManager independently from the context of the RViz2 application.

The YamlConfigReader class also needs to be moved to the public API to allow runtime configuration of the VisualizationManager, for example to add a Grid plugin.

This partially answers the questions raised in #645.

### CODE REVIEW

**Comment by JafarAbdi** [comment]
This's also needed for the [moveit_setup_assistant](https://github.com/ros-planning/moveit2/tree/main/moveit_setup_assistant) & [moveit_task_constructor_visualization](https://github.com/ros-planning/moveit_task_constructor/) port to ROS2

**Review by clalancette — APPROVED** [review]
This seems completely reasonable to me, so I'm going to go ahead and approve and run CI on it.  @jacobperron @mjeronimo any thoughts/questions/objections?

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13795/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8665/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11506/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13886/)

**Comment by jacobperron** [comment]
No objections here. I'm can't think of any negative side-effects at the moment.

**Comment by clalancette** [comment]
I'm going to hold off on merging until we get Windows CI back up and running (hopefully later today).  If there is going to be a problem here, it will be with Windows.

**Comment by schornakj** [comment]
Sounds good!

@clalancette @jacobperron out of curiosity, what kinds of changes to the API would you consider objectionable?

**Comment by clalancette** [comment]
> @clalancette @jacobperron out of curiosity, what kinds of changes to the API would you consider objectionable?

In this case, it's not really a question of being objectionable.  It's just that Windows is very picky about linkage between modules, and when you make functions public you often have to add the `dllexport` tag to them (which we've hidden behind macros).  So that's the major reason I want Windows CI to pass before merging.

**Pull request merged**
