### PR TITLE
Modify access specifier to protected or public for the scope of processMessage() member function

### PR DESCRIPTION
**Pull request by hyunseok-yang**
- pose_display, pose_with_covariance_display and relative_humidity_display

### CODE REVIEW

**Comment by hyunseok-yang** [comment]
hello, anybody know why this message occured?
**_Category 'whitespace/end_of_line' errors found: 1_**

**Comment by hyunseok-yang** [comment]
> hello, anybody know why this message occured? **_Category 'whitespace/end_of_line' errors found: 1_**

I guess I found by myself. there was empty whitespace on the empty line :)

**Comment by Yadunund** [comment]
Could you retarget this PR to `rolling`? Our practice is to merge any new changes into `rolling` branch first which we will then backport to other distro branches if the changes do not break API/ABI.

**Comment by hyunseok-yang** [comment]
> 

Ok sure!

**Comment by hyunseok-yang** [comment]
> Could you retarget this PR to `rolling`? Our practice is to merge any new changes into `rolling` branch first which we will then backport to other distro branches if the changes do not break API/ABI.


@Yadunund 

I created another separated branch for rolling and make PR. 
https://github.com/ros2/rviz/pull/984

**Comment by clalancette** [comment]
Given that we have #984 now, I'm going to close this one out.

**Pull request closed without merging**
