### PR TITLE
points_marker: fix bug where points are never cleared

### LINKED ISSUE #790: major performance issues marker cube_list
I decided to crosspost this from [https://answers.ros.org/question/389501/rviz2-performance-issues-with-cube_list-marker/](https://answers.ros.org/question/389501/rviz2-performance-issues-with-cube_list-marker/) as I did some more debugging in the meantime and at this point I think it is more of a bug report than the result of bad programming.

In foxy (and dashing, just to sort out #773) I encounter serious performance issues when trying to publish a `visualization_msg::msg::Marker` with some cubes. I tested with amounts between `20.000` and `1.000.000` cubes. In rviz2, even the lower bound of 20.000 cubes makes rviz almost unusable. Camera movement and interaction barely works. At the same time I ran rviz1 receiving the same topic through the ros2 bridge and everything is smooth, almost up to a million cubes. 

My debugging included:

- check rviz debug output -> GPU is used and works fine
- Sending a delete_all marker before every update makes no difference (sorts out #631)
- compile rviz2 from source instead of the -> No difference except I noticed that it is not built as "Release" per default. This seems strange but the release build does only make a small difference.
- qos settings, queue size -> no significant effect
- ros1 bridge -> everything smooth

At this point ros2 became almost unusable. We need to use some mapping libraries and I have no idea how to get a decent visualization if it can't handle ~50000 cubes properly.

I was wondering if the issue is maybe not so much rviz related but an effect of the slow deserialization issues when using "array-of-structs" design as explained in here: https://discourse.ros.org/t/ros2-speed/20162/19

Any ideas or possible improvements / tuning tricks are greatly appreciated. I used the following example code adapted from the basic ros2 publisher minimal example:

```
#include "rclcpp/rclcpp.hpp"
#include <visualization_msgs/msg/marker.hpp>

using namespace std::chrono_literals;

static constexpr int pt_count = 30; // 27000 points

class CubePublisher : public rclcpp::Node
{
  public:
    CubePublisher() : Node("cube_publisher")
    {
        publisher_ = this->create_publisher<visualization_msgs::msg::Marker>("/cubes", 10);
        timer_ = this->create_wall_timer(3000ms, std::bind(&CubePublisher::timer_callback, this));
    }

  private:
    void timer_callback()
    {
        visualization_msgs::msg::Marker marker;

        marker.id                 = 0;
        marker.type               = visualization_msgs::msg::Marker::CUBE_LIST;
        marker.scale.x            = 0.25;
        marker.scale.y            = 0.25;
        marker.scale.z            = 0.25;
        marker.color.a            = 1.0;
        marker.pose.orientation.w = 1.0;
        marker.frame_locked       = true;

        geometry_msgs::msg::Point cube_center;

        for (int i = 0; i < pt_count; ++i)
        {
            for (int j = 0; j < pt_count; ++j)
            {
                for (int k = 0; k < pt_count; ++k)
                {
                    cube_center.x = i / 2.0;
                    cube_center.y = j / 2.0;
                    cube_center.z = k / 2.0;

                    marker.points.push_back(cube_center);
                }
            }
        }

        marker.header.frame_id = "map";
        marker.header.stamp    = this->get_clock()->now();
        marker.action          = visualization_msgs::msg::Marker::ADD;

        RCLCPP_INFO_STREAM(this->get_logger(), "Publishing " << marker.points.size() << " cubes.");
        publisher_->publish(marker);
    }
    rclcpp::TimerBase::SharedPtr timer_;
    rclcpp::Publisher<visualization_msgs::msg::Marker>::SharedPtr publisher_;
};

int main(int argc, char *argv[])
{
    rclcpp::init(argc, argv);
    rclcpp::spin(std::make_shared<CubePublisher>());
    rclcpp::shutdown();
    return 0;
}
```

### PR DESCRIPTION
**Pull request by AndreasR30**
Hello,

this fixes a bug where a vector of points is never cleared. With each step more and more points are added. This fixes  #790 and maybe other issues with Marker in rviz. The example node in #790 works fine after this pull request.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
This seems like a reasonable bugfix to me, thanks.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18100/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12632/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18744/)

**Comment by james-yoo** [comment]
Hi,
Please backport this patch to humble branch.

Thanks

**Comment by clalancette** [comment]
@mergifyio backport humble

**Pull request merged**
