### PR TITLE
Ardent patch1 release

### PR DESCRIPTION
**Pull request by wjwwood**
Summary of changes:

- numerous changes to support Windows
- fixed an issue with docking windows initially
- added camera display
- moved to ogre 1.10.11
- (re)migrated TF display
- fixed a potential memory leak
- added image display
- moved to assimp 4.1.0
- moved point cloud displays to `rviz_default_plugins`

(updated changes):

- fixed rendering of point clouds where valid points were not rendered
- fixed a crash that occurred when removing a display
- port polygon display
- make rviz runnable with `ros2 run`
- disable robot model until it is properly ported
- various other fixes
- disable AA on Windows to workaround bug with multiple render windows for now

It will affect API and ABI, but rviz is not considered stable in ardent.

Connects to ros2/ros2#454

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
Major findings where we're unsure whether we can fix now:
- The following steps lead to a segfault when cleaning up the DisplayGroupVisibility property when closing rviz (both Windows and Linux):
-- Add Camera Display
-- Add Image Display (more than thrice)
-- Close the application (don't save or do save the config).
This is a weird issue, but we could only recreate it on closing. On Windows, it's a bit annoying as you get the "RViz stopped working" window.
- Adding a camera display and quickly adding a few image displays (use "duplicate") can result in an uncaught exception on both Windows and Linux. This seems to be a race condition maybe inside ogre with multiple viewports. It's unlikely that many users will ever see this problem and there might not be much we can do.

Minor findings:
- When initializing a camera display, the camera is set to a specific position above the grid, showing the default scene. When making the window invisible and visible again, that position changes. This looks a bit weird but doesn't stop functionality
- On Windows, editing a combobox (take e.g. the PointCloud display and edit the topic name), a warning gets added to the console:
`rviz_common::properties::EditableComboBox::setProperty: Property "currentText" invalid, read-only or does not exist`
This can be eliminated by eliminating the class `rviz_common::ComboBox` with apparently no change in functionality.
- Using the IntensityPCTransformer, the default visibility of some properties is not correct although it seems to be correctly set (autocompute intensity property is checked, but the manual min and max values are still visible, a similar problem is seen with the rainbow property).

I would convert all findings that we don't fix to issues after the release.

**Comment by greimela-si** [comment]
The PRs to be included into the release
- [x] #189 fixes the broken PointCloud2 display
- [x] #191 fixes a crash regarding the Camera display
- [x] #195 fixes the segfault when adding and removing image displays
- [x] #196 fixes some warnings regarding the pluginlib
- [x] #198 allows running rviz2 using `ros2 run`
- [x] #199 disables anti-aliasing on Windows

**Comment by Martin-Idel-SI** [comment]
We're just updating our comments when something new comes up or we find a fix for any of the problems.

**Comment by Martin-Idel-SI** [comment]
@wjwwood We've now done some extensive testing and these are all issues we found.

Please tell us which issues you think we should still try to fix or whether there is anything else, otherwise we're done.

**Comment by wjwwood** [comment]
> Please tell us which issues you think we should still try to fix or whether there is anything else, otherwise we're done.

I think the plan is to move forward with the current state (sans anything still needing review from me).

Thanks for helping test it out!

**Pull request merged**
