### PR TITLE
Remove the loading_ascii_stl_files_fail

### PR DESCRIPTION
**Pull request by clalancette**
In assimp version 5.2.2 and earlier (i.e. what is in Ubuntu Jammy), attempting to load ASCII STL files through assimp fails.  However, in assimp version 5.3.1 and later (what is in Ubuntu Noble and RHEL-9), attempting to load ASCII STL files through assimp succeeds.  Because this is functionality that might reasonably work, but won't work on all platforms, just remove the test.

This should solve the problem preventing https://github.com/ros2/ci/pull/735 from being merged.  @cottsay FYI.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20103/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14545/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20818/)

**Comment by ahcorde** [comment]
@clalancette should we backport this to Humble or Iron ?

**Comment by clalancette** [comment]
> @clalancette should we backport this to Humble or Iron ?

We should backport to Iron, yes, because it also uses RHEL-9.  It shouldn't be required for Humble.

**Comment by clalancette** [comment]
@Mergifyio backport iron

**Pull request merged**
