### PR TITLE
Do not block visualization manager updates when opening the display panel dialog

### LINKED ISSUE #793: ROS callbacks not processed if Qt dialog is open
To reproduce, visualize some data in Rviz (e.g. camera images, laser scans, etc) and then open the "add new display" dialog (Ctrl+N). You should notice that the displays stop updating. You should also notice that time stops updating in RViz.

This does not only affect displays, but also other ROS communication, for instance trying to set ROS parameters on RViz while a dialog is open causes the set parameter service call to block until the dialog is closed (or a timeout occurs).

I think the expected behavior should be that ROS callbacks are not blocked by Qt (at least ROS parameter updates should not be blocked).

I've noticed this bug is triggered by the "add new display" and "add a new tool" dialogs, but _not_ from the "about" dialog (accessed from the "help" menu, Alt+H then Alt+A).

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/rviz/issues/793.

### CODE REVIEW

**Comment by clalancette** [comment]
In theory I'm on board with this, but you might want to have a look at https://github.com/ros-visualization/rviz/pull/631, https://github.com/ros-visualization/rviz/issues/1606, https://github.com/ros-visualization/rviz/pull/1639, and https://github.com/ros-visualization/rviz/issues/1641 where similar things have been tossed around in the original RViz for years.  Your suggested solution is different, so it may solve the problems, but we should do some testing of the other problems reported.

**Comment by ivanpauno** [comment]
According to #601, the idea of stopping the world when openning a dialog was intentional.
I don't see how that solves the reported problem:

> This fixes the problem that rviz becomes effectively unusable when the update/render cycle takes too long (e.g. while showing high-frequency point cloud data).

was the idea to open a dialog when rviz gets unusable so you can remove the display causing the issue?

If that was the intention, it looks like a really weird idea.
The solution applied to noetic looks better, though I would like to test https://github.com/ros-visualization/rviz/issues/1641.

**Comment by clalancette** [comment]
> > 
> was the idea to open a dialog when rviz gets unusable so you can remove the display causing the issue?

Good question; I don't know :).

> If that was the intention, it looks like a really weird idea.

But yeah, I agree, it seems weird.

**Comment by ivanpauno** [comment]
I've (partially) reverted https://github.com/ros-visualization/rviz/pull/631.
I've tried to reproduce the issue reported in https://github.com/ros-visualization/rviz/issues/1641 and I couldn't.

I think that deleting this `stopUpdate()/startUpdate()` calls is fine.
If this reintroduces a problem, blocking updates while a dialog is open is probably not the right solution and we will have to figure out something else (or if that's the right solution, maybe we want to be spinning a ros executor somewhere else).

**Comment by ivanpauno** [comment]
@jacobperron friendly ping

**Review by jacobperron — APPROVED** [review]
lgtm

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15624/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10305/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13292/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15841/)

**Pull request merged**
