### PR TITLE
Fix splash screen and help panel

### LINKED ISSUE #59: [rviz_common] fix help panel and splashscreen
See:

- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.hpp#L100-L108
- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.cpp#L138-L143
- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.cpp#L241-L246
- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.cpp#L1147-L1152

These may rely on the #49 solution and will require replacing `boost::filesystem` too.

### PR DESCRIPTION
**Pull request by botteroa-si**
Closes #59.

With this PR the splash screen (with the relative command line option) and the help panel are re-enabled. 
For what concerns the help panel content, the information about not yet ported tools and view controllers has been commented out for the moment.

### CODE REVIEW

**Comment by botteroa-si** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4534/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1451/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4613/)

**Comment by botteroa-si** [comment]
@wjwwood, the failing of Linux and macOS seems unrelate to our changes. Here a new CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4554/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1465/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3739/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4635/)

**Comment by botteroa-si** [comment]
New CI after the non trivial rebase:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4602/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1504/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3783/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4680/)

**Comment by Martin-Idel-SI** [comment]
CI after rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4614/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1515/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3798/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4692/)

New mac:
* macOS [Build Status](https://ci.ros2.org/job/ci_osx/3830/)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
