### PR TITLE
[eloquent backport] Remove uncessary call to render scene (#490)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #490 to Eloquent

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9817/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5442/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7985/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9680/)

### CODE REVIEW

**Comment by vmanchal1** [comment]
Any update on when this can be merged? Is the fix working? Thank you for the help.

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
I'm sorting out some of the `eloquent` CI issues, this should not have an impact, so you can go ahead and merge it.

**Comment by vmanchal1** [comment]
Thank you for merging this. I am new to ROS2, still trying to understand the release cycle. Can someone tell me when this fix will make it to the release?

**Comment by jacobperron** [comment]
@vmanchal1 You can expect the change to make it as part of the next Eloquent patch release, which is typically announced on [discourse](https://discourse.ros.org/c/release/eloquent/57). I don't know the timeline for the next patch release, but @mjcarroll may be able to give you an update.

**Pull request merged**
