### PR TITLE
Wrench accepth nan values fix

### PR DESCRIPTION
**Pull request by ahcorde**
Related with this issue https://github.com/ros2/rviz/issues/1139

### CODE REVIEW

**Comment by firesurfer** [comment]
@ahcorde Unfortunately I am not able to build your branch on my ros2 iron setup.


I guess something about the ` ignition_math6_vendor` changed between iron and rolling
```
Starting >>> rviz_default_plugins
--- stderr: rviz_default_plugins                            
CMake Error at CMakeLists.txt:64 (find_package):
  By not providing "Findignition_math6_vendor.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "ignition_math6_vendor", but CMake did not find one.

  Could not find a package configuration file provided by
  "ignition_math6_vendor" with any of the following names:

    ignition_math6_vendorConfig.cmake
    ignition_math6_vendor-config.cmake

  Add the installation prefix of "ignition_math6_vendor" to CMAKE_PREFIX_PATH
  or set "ignition_math6_vendor_DIR" to a directory containing one of the
  above files.  If "ignition_math6_vendor" provides a separate development
  package or SDK, be sure it has been installed.

```

But the change in the code looks reasonable to me.

**Review by adityapande-1995 — APPROVED** [review]
Looks good with green CI, I'll try to build this locally.

**Comment by ahcorde** [comment]
> @ahcorde Unfortunately I am not able to build your branch on my ros2 iron setup.
> 
> I guess something about the ` ignition_math6_vendor` changed between iron and rolling
> 
> ```
> Starting >>> rviz_default_plugins
> --- stderr: rviz_default_plugins                            
> CMake Error at CMakeLists.txt:64 (find_package):
>   By not providing "Findignition_math6_vendor.cmake" in CMAKE_MODULE_PATH
>   this project has asked CMake to find a package configuration file provided
>   by "ignition_math6_vendor", but CMake did not find one.
> 
>   Could not find a package configuration file provided by
>   "ignition_math6_vendor" with any of the following names:
> 
>     ignition_math6_vendorConfig.cmake
>     ignition_math6_vendor-config.cmake
> 
>   Add the installation prefix of "ignition_math6_vendor" to CMAKE_PREFIX_PATH
>   or set "ignition_math6_vendor_DIR" to a directory containing one of the
>   above files.  If "ignition_math6_vendor" provides a separate development
>   package or SDK, be sure it has been installed.
> ```
> 
> But the change in the code looks reasonable to me.

Did you install `sudo apt-get install ros-rolling-ignition-math6-vendor` ?

**Comment by firesurfer** [comment]
I have the corresponding `iron` package installed as our whole code base is built against iron.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20343/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14752/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21089/)

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble iron

**Pull request merged**
