### PR TITLE
Migrate 2D Nav Goal tool

### LINKED ISSUE #215: Migrate 2D Nav Goal tool
Migrate the `2D Nav Goal` tool to RViz for ROS2.

Internal name: `rviz::GoalTool`

### PR DESCRIPTION
**Pull request by botteroa-si**
Closes #215.

This PR consists of the migration of the Goal Tool (together with the Pose tool), the addition of tests and refactoring.
In particular, we also slightly changed the behaviour of the tool when one, after having clicked on the xy plane, releases the mouse in a point that doesn't intersect this plane: in RViz 1 the green arrow generated by the Pose Tool would just stay visible and the nav goal tool would remain selected, until a new mouse click event happens. Now the pose message is published using the current orientation of the Pose Tool arrow. (This fix also prevents an assert to fail and RViz to crash).

### CODE REVIEW

**Comment by botteroa-si** [comment]
CI: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4628/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1526/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3813/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4704/)

**Comment by botteroa-si** [comment]
New CI after rebase:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4653/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1545/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3847/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4729/)

**Comment by botteroa-si** [comment]
@wjwwood, as for the PR #295, we added the last commit ([6e1ba86](https://github.com/ros2/rviz/pull/294/commits/6e1ba866a8b5419eb7224a3b951836dbbf8c85f1)) only the make the tests pass. This commit resolves an undetected merge error from last night and will be published as a pr of its own. The last commit will cause a conflict once the other pr is merged. Simply remove the last commit from this pr before merging will work.

**Comment by botteroa-si** [comment]
New CI after force push (the new commit ([b86a7c1](https://github.com/ros2/rviz/pull/294/commits/b86a7c115bab1c2511e9b0f610b405b147490dd2)) fixes a bug introduced by the fix provided by the PR #298):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4657/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1548/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3851/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4732/)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
