### PR TITLE
TF Display migration

### LINKED ISSUE #102: Migrate TFDisplay

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Closes #102 

Restores all functionality to tf_display. Overhaul of MovableText.

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3900/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1018/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3223/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3993/)

**Comment by Martin-Idel-SI** [comment]
I tried to rerun the build several times, but it always failed on Windows in the `urdfdom` package. Since this has nothing to do with rviz, I don't know what to do about it.

**Comment by wjwwood** [comment]
@Martin-Idel-SI I'm not sure what the issue is, I'm going to create a new ros2.repos file with this branch and see if I can reproduce the issue. I would have expected to see it on nightlies, but perhaps I missed a hiccup while on vacation:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1028/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3233/) (unrelated test failure)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4003/)

**Review by wjwwood — APPROVED** [review]
lgtm, though I don't fully understand the reason behind changing the way movable text works, the transformation looks ok to me.

**Pull request merged**
