### PR TITLE
Use conversions and alpha in other displays

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
This is a cleanup PR: We harmonise transform behaviour, use message conversions and our alpha blending everywhere, where we couldn't use it till now (due to merge conflicts, etc.)

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4749/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1617/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3937/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4809/)

**Comment by Martin-Idel-SI** [comment]
CI after rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4768/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1633/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3954/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4825/)

**Comment by Martin-Idel-SI** [comment]
CI after rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4787/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1649/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3970/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4842/)

**Comment by botteroa-si** [comment]
New CI after rebase:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4814/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1675/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3998/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4867/)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
