### PR TITLE
Migrate camera display

### LINKED ISSUE #94: Migrate CameraDisplay

### PR DESCRIPTION
**Pull request by greimela-si**
Closes #94.

Migrates the camera display to RViz 2.

### CODE REVIEW

**Comment by greimela-si** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3901/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1019/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3224/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3994/)

**Comment by wjwwood** [comment]
Needs rebase.

**Comment by greimela-si** [comment]
On it

**Comment by greimela-si** [comment]
CI after Rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3910/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1029/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3234/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4004/)

It looks like the Windows failure is not connected to these changes

**Review by wjwwood — APPROVED** [review]
lgtm

**Pull request merged**
