### PR TITLE
TimePanel port

### PR DESCRIPTION
**Pull request by neumann-nico**
This pull request adds a working version of the Time Panel to rviz_common.
Tested on Ubuntu 20.04 ROS foxy and Ubuntu 18.04 ROS eloquent.

### CODE REVIEW

**Review by jacobperron — COMMENTED** [review]
Trying out this PR, when I start RViz, without any persistent RViz config, no panels are loaded and the render window doesn't appear. I'm on Ubuntu Focal.

I'm not sure where the bug is. Does this work for you?

**Review by wjwwood — APPROVED** [review]
lgtm with CI and @jacobperron's issue addressed

I didn't test it locally.

**Comment by neumann-nico** [comment]
@jacobperron @wjwwood Thanks for the review.

I tested it again and have the same bug that panels are not loaded. The problem is that the QMainWindow State needs to be updated too.

If I comment out the time panel in the default config again, open rviz2 and add the time panel over the gui it works fine. But saving this configuration file leads to a lot of changes also in other panels that may not be necessary. I'm not sure how to handle it properly. Maybe you have an idea @jacobperron.

I just fixed another bug: When saving the configuration and restarting rviz2 with activated time panel I get this error which results in a crash:

```bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  can't subtract times with different time sources [1 != 2]
```

The crash happens in this part of the code:
```c++
double VisualizationManager::getROSTimeElapsed()
{
  // TODO(wjwwood): why does this function return now - begin, whereas the getWallClockElapsed
  //                returns a pre-calculated elapsed value?
  //                figure out how this function is being used and make these consistent
  // return (frame_manager_->getTime() - ros_time_begin_).nanoseconds() / 1e9;  // crashed here
  return static_cast<double>(ros_time_elapsed_) / 1e9;                          // changed to this line
}
```

I tried to return the `ros_time_elapsed_` variable that is calculated in the `updateTime` method, instead of returning the calculation above and it fixes the crash.

```c++
void VisualizationManager::updateTime()
{
  rclcpp::Clock clock;  // TODO(wjwwood): replace with clock attached to node for ROS Time
  if (ros_time_begin_.nanoseconds() == 0) {
    ros_time_begin_ = clock_->now();
  }

  ros_time_elapsed_ = (clock_->now() - ros_time_begin_).nanoseconds();

  if (wall_clock_begin_.time_since_epoch().count() == 0) {
    wall_clock_begin_ = std::chrono::system_clock::now();
  }

  wall_clock_elapsed_ = std::chrono::system_clock::now() - wall_clock_begin_;
}
```

Tested on foxy branch (ROS foxy + Ubuntu 20.04) and on eloquent branch (ROS eloquent + Ubuntu 18.04).

**Comment by jacobperron** [comment]
It would be nice to have the TimePanel on by default.

Sorry, I'm starting a vacation and won't be able to take a closer look until a couple weeks from now. I can take a look then, if this ticket is still open.

**Review by jacobperron — APPROVED** [review]
Seems to be working now (I guess the issue was caused by an incorrect indentation level in the default config?).

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12278/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7252/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9996/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12182/)

**Comment by neumann-nico** [comment]
@jacobperron Thanks for approving!
Yes the issue was caused by an incorrect indentation. 

The time panel is activated and running by default now. That's how you wanted to have it?
I tried to let the panel activated but hide it by default, but somehow I couldn't manage to change it.

**Comment by jacobperron** [comment]
@neumann-nico I think having the time panel active by default is good. This is also the default in ROS 1, I think.

Thanks for the feature!

**Pull request merged**
