### PR TITLE
add missing qt5base-dev build depend to rviz2

### PR DESCRIPTION
**Pull request by wjwwood**
This necessary to work around issues with building the debs and finding libraries on the library path at runtime.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
lgtm :+1:

**Comment by wjwwood** [comment]
I've started some ci packaging jobs to test if this fixes the linking:

- Linux: [Build Status](http://ci.ros2.org/job/ci_packaging_linux/57/)
- macOS: [Build Status](http://ci.ros2.org/job/ci_packaging_osx/19/)

Simultaneously, @nuclearsandwich is testing the deb's being built. In all three cases I'll spot check rviz for library path issues.

If the debs build and the library paths look ok, then we can either merge this directly or I can start a round of normal CI and merge after that (assuming it's green), but I wanted to do the packaging jobs first since they're faster.

**Comment by wjwwood** [comment]
Unfortunately that doesn't seem to have fixed the yaml-cpp issue with the binary on macOS. Looking into it now.

**Comment by nuclearsandwich** [comment]
http://build.ros2.org/view/all/job/Abin_uX64__rviz2__ubuntu_xenial_amd64__binary/9/

First successful build of rviz2! 🎉

**Comment by wjwwood** [comment]
Ok, I had to make the env hooks relocatable. I messed it up when I was originally trying to do the env hooks without ament. New packaging jobs:

- Linux: [Build Status](http://ci.ros2.org/job/ci_packaging_linux/58/)
- macOS: [Build Status](http://ci.ros2.org/job/ci_packaging_osx/20/)

**Comment by wjwwood** [comment]
@mikaelarguedas Is this related to the `rosidl` pr that just went in?
 http://ci.ros2.org/job/ci_packaging_osx/20/console

**Comment by wjwwood** [comment]
Ok, fixed the tag, packaging CI:

- Linux: [Build Status](http://ci.ros2.org/job/ci_packaging_linux/59/)
- macOS: [Build Status](http://ci.ros2.org/job/ci_packaging_osx/21/)

**Comment by wjwwood** [comment]
The macOS packaging is done and seems to work fine (for `rviz2_app` at least).

**Comment by wjwwood** [comment]
I'd like to wait for the linux job to finish and then test it, but I have high confidence that it will work since the mac one does.

**Comment by mikaelarguedas** [comment]
> Ok, fixed the tag

 thanks ! sorry about that

**Comment by nuclearsandwich** [comment]
This allows the entire suite rviz packages to build on AMD64.

**Comment by wjwwood** [comment]
Ok, rviz runs, but doesn't open up for me because of a known issue with rviz2 on VM's (lacks required glx version), can someone else test the latest linux binary real quick?

**Comment by wjwwood** [comment]
Ok, I tested on my desktop, lgtm.

**Pull request merged**
