### PR TITLE
Fix GCC 8 compiler error.

### PR DESCRIPTION
**Pull request by allenh1**
GCC 8 has some rather strong feelings about the `memcpy` call seen here. This changes it to a for loop so that it uses the `=` operator to copy data.

### CODE REVIEW

**Comment by wjwwood** [comment]
Can you provide the actual error from the compiler too?

I'll have to check this one closely, as the `operator=` is not necessarily equivalent to `memcpy`, but it might be.

**Comment by allenh1** [comment]
@wjwwood Here you go.

```
Process package 'rviz_rendering' with context:
--------------------------------------------------------------------------------
 source_space => /home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering
  build_space => /home/allenh1/ros2_ws/build/rviz_rendering
install_space => /home/allenh1/ros2_ws/install
   make_flags => -j8, -l8
  build_tests => False
--------------------------------------------------------------------------------
+++ Building 'rviz_rendering'
Running cmake because arguments have changed.
==> '. /home/allenh1/ros2_ws/build/rviz_rendering/cmake__build.sh && /usr/bin/cmake /home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering -DBUILD_TESTING=0 -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/home/allenh1/ros2_ws/install' in '/home/allenh1/ros2_ws/build/rviz_rendering'
-- The C compiler identification is GNU 8.0.0
-- The CXX compiler identification is GNU 8.0.0
-- Check for working C compiler: /home/allenh1/bin/gcc
-- Check for working C compiler: /home/allenh1/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/allenh1/bin/g++
-- Check for working CXX compiler: /home/allenh1/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 0.0.3 (/home/allenh1/ros2_ws/install/share/ament_cmake/cmake)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Override CMake install command with custom implementation using symlinks instead of copying resources
-- Found ament_cmake_gtest: 0.0.3 (/home/allenh1/ros2_ws/install/share/ament_cmake_gtest/cmake)
-- Found ament_index_cpp: 0.0.3 (/home/allenh1/ros2_ws/install/share/ament_index_cpp/cmake)
-- Found rviz_ogre_vendor: 1.0.0 (/home/allenh1/ros2_ws/install/share/rviz_ogre_vendor/cmake)
-- Setting OGRE_DIR to: '/home/allenh1/ros2_ws/install/share/rviz_ogre_vendor/cmake/../../../opt/rviz_ogre_vendor/lib/OGRE/cmake'
-- Found OGRE
--   static     : ON
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus
--   media      : /home/allenh1/ros2_ws/install/opt/rviz_ogre_vendor/share/OGRE/Media
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/allenh1/ros2_ws/build/rviz_rendering
==> '. /home/allenh1/ros2_ws/build/rviz_rendering/cmake__build.sh && /usr/bin/make -j8 -l8' in '/home/allenh1/ros2_ws/build/rviz_rendering'
Scanning dependencies of target rviz_rendering_automoc
[  4%] Automatic moc for target rviz_rendering
Generating moc_render_window.cpp
[  4%] Built target rviz_rendering_automoc
Scanning dependencies of target rviz_rendering
[  9%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/geometry.cpp.o
[ 14%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/apply_visibility_bits.cpp.o
[ 19%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/axes.cpp.o
[ 23%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/arrow.cpp.o
[ 28%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/logging.cpp.o
[ 33%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/movable_text.cpp.o
[ 38%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/object.cpp.o
[ 42%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/ogre_logging.cpp.o
[ 47%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/orthographic.cpp.o
[ 52%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/render_system.cpp.o
[ 57%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/render_window.cpp.o
[ 61%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/ogre_render_window_impl.cpp.o
[ 66%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/resource_config.cpp.o
[ 71%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/shape.cpp.o
[ 76%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/grid.cpp.o
[ 80%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/string_helper.cpp.o
[ 85%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/point_cloud.cpp.o
[ 90%] Building CXX object CMakeFiles/rviz_rendering.dir/src/rviz_rendering/point_cloud_renderable.cpp.o
[ 95%] Building CXX object CMakeFiles/rviz_rendering.dir/rviz_rendering_automoc.cpp.o
/home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering/src/rviz_rendering/point_cloud.cpp: In member function ‘void rviz_rendering::PointCloud::insertPointsToPointList(std::vector<rviz_rendering::PointCloud::Point>::iterator, std::vector<rviz_rendering::PointCloud::Point>::iterator)’:
/home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering/src/rviz_rendering/point_cloud.cpp:497:61: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct rviz_rendering::PointCloud::Point’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
   memcpy(begin, &*start_iterator, sizeof(Point) * num_points);
                                                             ^
In file included from /home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering/src/rviz_rendering/point_cloud.cpp:31:
/home/allenh1/ros2_ws/src/ros2/rviz/rviz_rendering/include/rviz_rendering/point_cloud.hpp:125:10: note: ‘struct rviz_rendering::PointCloud::Point’ declared here
   struct Point
          ^~~~~
cc1plus: all warnings being treated as errors
CMakeFiles/rviz_rendering.dir/build.make:446: recipe for target 'CMakeFiles/rviz_rendering.dir/src/rviz_rendering/point_cloud.cpp.o' failed
make[2]: *** [CMakeFiles/rviz_rendering.dir/src/rviz_rendering/point_cloud.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rviz_rendering.dir/all' failed
make[1]: *** [CMakeFiles/rviz_rendering.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

<== Command '. /home/allenh1/ros2_ws/build/rviz_rendering/cmake__build.sh && /usr/bin/make -j8 -l8' failed in '/home/allenh1/ros2_ws/build/rviz_rendering' with exit code '2'
<== Command '. /home/allenh1/ros2_ws/build/rviz_rendering/cmake__build.sh && /usr/bin/make -j8 -l8' failed in '/home/allenh1/ros2_ws/build/rviz_rendering' with exit code '2'

```

> I'll have to check this one closely, as the operator= is not necessarily equivalent to memcpy, but it might be.

Absolutely -- I'm definitely not sure these operations  are equivalent.

**Comment by anhosi** [comment]
I believe the main point of the funciton `insertPointsToPointList` is the single `memcpy` instead of potentially many copies of single points. May be @wjwwood has more information on that.

If we replace this I would suggest to replace the whole function with
```
points_.insert(points_.cend(), start_iterator, stop_iterator);
```

**Comment by wjwwood** [comment]
@anhosi I was leaning to something similar, though I don't know how the performance will be impacted.

I'm going to test and, if working, take this pr and then make a follow up issue to investigate cleaning this particular segment of code up.

**Comment by wjwwood** [comment]
Ok, I tested this locally, and it does seem to work. To test it I ported this `send_lots_of_points_node` from the old `rviz` package and put it in the `rviz2` package for now. It doesn't install, but can be run from the build folder.

To test this I opened a few shells with the ros2 workspace sourced and then I:

- ran `launch ros2_ws/install/share/dummy_robot_bringup/launch/dummy_robot_bringup.py`
- ran `./build/rviz2/test/tools/send_lots_of_points_node`
- ran `rviz2_app`
  - then added the PointCloud display and a Tf display (for fun) and then changed the fixed frame to `world`

CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3766/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/909/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3100/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3855/)

**Review by wjwwood — APPROVED** [review]
Thanks for looking into @allenh1.

**Pull request merged**
