### PR TITLE
Migrate point stamped display

### LINKED ISSUE #83: Migrate PointStampedDisplay

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Closes #83 

Note that I completely deleted the "point_visual", since it was just a wrapper around a sphere shape.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4539/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1452/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3725/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4614/)

EDIT: MacBuild not our failure, but here is a new one:
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3746/)

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI after rebase:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4608/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1509/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3791/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4685/)

**Comment by dhood** [comment]
@Martin-Idel-SI you probably noticed already but you'll need to update your repos file to include https://github.com/ros2/ros2/pull/488

**Comment by Martin-Idel-SI** [comment]
@dhood: Thanks. Yes, I noticed.

Here is a new CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4609/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1510/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3792/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4687/)

**Comment by anhosi** [comment]
New CI after rebase (restricted to rviz):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4620/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1520/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3806/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4698/)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
