### PR TITLE
Switch from ROS_TIME to SYSTEM_TIME on rclcpp::Time construction

### PR DESCRIPTION
**Pull request by AustinMooreT**
This potentially fixes the issue mentioned here: https://github.com/ros2/rviz/issues/1116
I'm not sure if this is the correct way to go about it.

### CODE REVIEW

**Comment by AiVerisimilitude** [comment]
I mentioned in the issue post, but I believe the better way would be to change the affected comparison calls instead of the clock type.

The reasoning is that the previous behavior calls the implicit constructor from a header stamp, which would default to a RCL_ROS_TIME clock (instead of RCL_SYSTEM_TIME):
```cpp
  RCLCPP_PUBLIC
  Time(
    const builtin_interfaces::msg::Time & time_msg,
    rcl_clock_type_t clock_type = RCL_ROS_TIME);
```

The issue here that you found was that a comparison to a default clock was being made that should have been clock agnostic. Previously it was comparing a stamp to a rclcpp::Time which decayed the time object to a builtin_interfaces::msg::Time before doing the comparison (which is a clock agnostic comparison) while now, it is using a clock sensitive comparison of two rclcpp::Time objects.

We can fix the comparison by using the builtin_interfaces::msg::Time comparison operator (like before) by doing something like:

```cpp
frame_locked_ = (message.header.stamp == builtin_interfaces::msg::Time());
```

Let me know if this makes sense to you.

Thanks for finding this and giving a shot at a fix :D

**Comment by AustinMooreT** [comment]
Your suggestion makes sense to me. I reverted the initial commit, and made the changes. I tested it on my local machine to make sure the exception was not being thrown still. Everything seemed to work ok.

**Comment by AiVerisimilitude** [comment]
Cool, looks good to me at least. I also went through [#1087](https://github.com/ros2/rviz/pull/1087/files) and these 2 were indeed the only comparisons affected that I found. 

Good stuff, thanks! :D

**Review by ahcorde — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20057/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14510/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20777/)

**Pull request merged**
