### PR TITLE
Add visibility to rviz default plugins

### LINKED ISSUE #280: Make code reuse for rviz_default_plugins possible
Other rviz plugin packages should be able to reuse code from rviz_default_plugins.
To make this work, the headers of rviz_default_plugins need to be made public and the dll symbols need to be exported.

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Closes #280 

This PR does the following:
- Move all headers in rviz_default_plugins to the include folder and add visibility
- Switch back to only building a shared library of `rviz_default_plugins`
- Remove all superfluous include guards (they were necessary when building and linking static libraries before)

We also tested on Mac, so it should work there too.

Minor issue: For most classes, the class is completely exported, marker classes needed to be exported function-wise. The reason is that the marker classes need to have typeinfo of `visualization_msgs::msg::Marker` available in their headers, however Windows complained that there was no dllexport for `visualization_msgs::msg::Marker`. This implies that Marker classes cannot be subclassed by clients.

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4570/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1480/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3757/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4657/)

**Comment by wjwwood** [comment]
> Minor issue: For most classes, the class is completely exported, marker classes needed to be exported function-wise. The reason is that the marker classes need to have typeinfo of visualization_msgs::msg::Marker available in their headers, however Windows complained that there was no dllexport for visualization_msgs::msg::Marker. This implies that Marker classes cannot be subclassed by clients.

That's expected I think. Many of our classes are only exported method by method rather than as whole classes.

**Review by wjwwood — APPROVED** [review]
lgtm

**Comment by wjwwood** [comment]
Unfortunately, all of the warning suppression is still needed, at least in my editor, which even if the rviz packages do not build with as strict compiler flags (perhaps it should), we should still leave them because other's using our headers might have stricter compiler flags too. I might make another pull request to undo these deletions.

**Pull request merged**
