### PR TITLE
use rcutils_get_env.

### LINKED ISSUE #856: replace custom get env logic in various places with rcutils_get_env()

### PR DESCRIPTION
**Pull request by fujitatomoya**
close https://github.com/ros2/ros2/issues/856

Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

- Note

all rviz related tests are pass,

```
> colcon test --packages-select rviz_visual_testing_framework rviz2 rviz_assimp_vendor rviz_common rviz_default_plugins rviz_ogre_vendor rviz_rendering rviz_rendering_tests
```

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@jacobperron 
CC: @dirk-thomas @clalancette

could you take a look when you got time?

**Review by clalancette — CHANGES_REQUESTED** [review]
Since we are now explicitly relying on `rcutils`, please add a build dependency to the package.xml and do a `find_package` in the CMakeLists.txt.

Otherwise, the code looks good.

**Comment by fujitatomoya** [comment]
@clalancette 

> Since we are now explicitly relying on rcutils, please add a build dependency to the package.xml and do a find_package in the CMakeLists.txt.

that is correct, thanks! it's done with https://github.com/ros2/rviz/pull/609/commits/77a5ac46bcda5b50a53d6995711c5d5e69758478

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12705/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7666/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10419/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12651/)

**Pull request merged**
