### PR TITLE
[Backport galatic] Removed some memory leaks in rviz_rendering and rviz_rendering_tests #710

### PR DESCRIPTION
**Pull request by ahcorde**
Backport #710

### CODE REVIEW

**Review by mjeronimo — APPROVED** [review]

**Comment by ahcorde** [comment]
` --packages-above-and-dependencies rviz2`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14829/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9579/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12495/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14984/)

**Comment by ahcorde** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14986/)

**Comment by ahcorde** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14987/)

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14835/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9585/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12501/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14992/)

**Pull request merged**
