### PR TITLE
Fix for mousewheel to zoom in/out

### LINKED ISSUE #605: Zoom with mouse wheel not working
In rviz2 version 8.2.0-1focal.20200911.234728 on Ubuntu I cannot zoom with the mouse wheel (default settings). Zooming with a right-click does work though.

I tried to track down this error, but when I compile rviz2, it links to my installation in `/opt/ros/foxy`.

Update: This problem still occurs in version 8.2.0-1focal.20200921.203534.

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #605

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

**Comment by iuhilnehc-ynos** [comment]
Hi, @jacobperron 

From https://github.com/ros2/rviz/blob/323378a27047f66ce6823e99b5a45172af6c6601/rviz_common/include/rviz_common/viewport_mouse_event.hpp#L95-L96
and message in the status bar "<b>Right-Click/Mouse Wheel:</b>: Zoom.  ", I think we need to use `e->angleDelta().y()` to instead of `e->angleDelta().x()` in https://github.com/ros2/rviz/blob/323378a27047f66ce6823e99b5a45172af6c6601/rviz_common/src/rviz_common/viewport_mouse_event.cpp#L67.  (Of course, we can also update the comment "/// Angle that the common horizontal mouse wheel was rotated " and tip message, such as "<b>Right-Click/Alt+Mouse Wheel:</b>: Zoom.  ".)

NOTE: https://doc.qt.io/qt-5/qwheelevent.html#angleDelta  (angleDelta().y() provides the angle through which the common vertical mouse wheel was rotated since the previous event)

**Comment by iuhilnehc-ynos** [comment]
friendly ping @jacobperron :no_bell:

**Review by jacobperron — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13046/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7994/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10770/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13028/) (unrelated warning)

**Pull request merged**
