### PR TITLE
Make rviz_assimp_vendor hack specific to Ubuntu Focal.

### LINKED ISSUE #535: Build fail on Ubuntu 18.04
I built ROS 2 foxy (master branch of [ros2/ros2](https://github.com/ros2/ros2/blob/master/ros2.repos)) from source code on Ubuntu 18.04.
(With release build: `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`)
However it failed while building package rviz_assimp_vendor. The error message is like below
```
--- stderr: rviz_assimp_vendor                                                                                                                                                                             
CMake Error at CMakeLists.txt:81 (message):
  failed to find assimpTargets.cmake as expected

---
Failed   <<< rviz_assimp_vendor	[ Exited with code 1 ]
```

I guess the error is related to [here](https://github.com/ros2/rviz/blob/ros2/rviz_assimp_vendor/CMakeLists.txt#L78). Ubuntu 18.04 can't find this file, so it generates error.
Although foxy only supports Ubuntu 20.04, maybe the path should not be fixed?

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This will keep it working on Ubuntu Bionic.

Fixes #535

### CODE REVIEW

**Comment by clalancette** [comment]
CI (just Linux):

* Linux Focal [Build Status](http://ci.ros2.org/job/ci_linux/10618/)
* Linux Bionic [Build Status](http://ci.ros2.org/job/ci_linux/10619/)

**Review by wjwwood — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks!

**Comment by dirk-thomas** [comment]
The current patch prevents building this package e.g. on Ubuntu 20.10 in the future or an Ubuntu derivate if it doesn't identify itself as 20.04 which will increase the maintenance effort. I suggest to instead invert the logic and detect 18.04 to work around for that officially not supported case.

**Comment by clalancette** [comment]
> The current patch prevents building this package e.g. on Ubuntu 20.10 in the future or an Ubuntu derivate if it doesn't identify itself as 20.04 which will increase the maintenance effort. I suggest to instead invert the logic and detect 18.04 to work around for that officially not supported case.

I'm not sure I agree.  Ubuntu Focal is the one-off distribution with the problem; presumably the next version of Ubuntu will have the fixed version of assimp, and thus we won't need the hack going forward.

**Pull request merged**
