### PR TITLE
[foxy] Fix interface link libraries in ogre vendor (#761)

### PR DESCRIPTION
**Pull request by jacobperron**
Backport #761 to Foxy.

### CODE REVIEW

**Review by audrow — APPROVED** [review]
Looks good to me! Should CI be run for this?

**Comment by jacobperron** [comment]
Yep, here's CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17023/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11583/)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/17454/)

**Comment by jacobperron** [comment]
Seems like this PR introduces new MSBuild warnings.

Running Windows CI on Foxy mainline for comparison: [Build Status](https://ci.ros2.org/job/ci_windows/17762/)

**Comment by jacobperron** [comment]
Nope, the MSBuild errors are also occurring on the default `foxy` branches.

**Pull request merged**
