### PR TITLE
[rviz_rendering] porting camera code from ogre_helpers

### PR DESCRIPTION
**Pull request by wjwwood**
This is still a work in progress, opening for visibility.

### CODE REVIEW

**Comment by anhosi** [comment]
Works for me as a preparation for future work. The linters `cpplint` and `uncrustify` fail for `rviz_rendering`. For `rviz_common` the linters do not run for me using `ament test --build-tests --only rviz_common --cmake-args -DCMAKE_BUILD_TYPE=Release`.
I would prefer to fix at least the linter errors in `rviz_rendering`.

**Comment by wjwwood** [comment]
@anhosi was this comment maybe intended for https://github.com/ros2/rviz/pull/19?

**Comment by anhosi** [comment]
@wjwwood yes, sorry. My above comment was indeed meant for #19.

**Comment by wjwwood** [comment]
Closing in favor of #32, looks like some of this code is dead code in rviz as well.

**Pull request closed without merging**
