### PR TITLE
Migrate XYOrbitViewController

### LINKED ISSUE #219: Migrate XY Orbit view controller
Migrate the `XY Orbit` view controller to RViz for ROS2.

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Closes #219 

This PR migrates the XYOrbitViewController and also updates the OrbitViewController.
In particular, we worked on consistency in "mimic" again, working with the originally intended behaviour.

We tried to enable "mimic" behaviour also when the camera was below the xy-plane, but didn't manage to have it working as above the xy-plane (sadly, it's not a symmetric problem).

CI: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4558/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1468/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3743/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4638/)

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
We added two small fixes and rebased onto current master. So a new CI is in order:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4582/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1489/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3765/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4665/)

**Comment by clalancette** [comment]
@Martin-Idel-SI FYI, your macOS build failed because of a Jenkins disconnect, and then the restart of it happened to get onto a node that is having trouble right now.  I've killed off the new job, so it would probably be best if you kick off a new macOS job on the build farm by hand.  Sorry for the disruption.

**Comment by Martin-Idel-SI** [comment]
@clalancette Thanks for the explanation. I'll restart:

* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3768/)

**Review by wjwwood — APPROVED** [review]
code changes lgtm, will merge with CI

**Comment by wjwwood** [comment]
I built and tested the controller out locally (on my macbook), looks good there too.

CI (using `--packages-up-to rviz2 rviz_rendering_tests rviz_visual_testing_framework`):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4590/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1497/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3774/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4672/)

**Comment by wjwwood** [comment]
Missed a cpplint issue:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4610/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1511/)
* macOS [Build Status](https://ci.ros2.org/job/ci_osx/3795/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4688/)

**Pull request merged**
