### PR TITLE
Set message type for ros topic display

### PR DESCRIPTION
**Pull request by wep21**
Set message type for ros topic display to show topic name candidates with combo box.

### CODE REVIEW

**Comment by wep21** [comment]
@clalancette could you review this, please?

**Comment by wep21** [comment]
@jacobperron @clalancette friendly ping

**Comment by jacobperron** [comment]
The change looks okay to me, but should we expect any difference in behavior when running rviz? I didn't notice any difference making wonder if there is just some dead code lying around.

**Comment by jacobperron** [comment]
Ah, I see. We were already setting the message type in MessageFilterDisplay:

https://github.com/ros2/rviz/blob/31380f8fe65695d4f92dc2846c29a2f0a982787f/rviz_common/include/rviz_common/message_filter_display.hpp#L63-L64

This PR does the same of the few default displays that are not using MessageFilterDisplay.

**Review by jacobperron — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15903/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10578/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13567/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16223/)

Uncrustify failures are fixed on the `ros2` branch.

**Comment by wep21** [comment]
@jacobperron Yes, this shows topic candidates whose type is the target topic type in combo box.
output

**Pull request merged**
