### PR TITLE
Clean code for Image display

### PR DESCRIPTION
**Pull request by penww**
Some cleanup:

- Considering duplicated code in multiple places, using a common function to handle YUV to RGB pixel conversion.
- Using `std::clamp()` instead of clamp expressions.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
I'm worried here about the performance, we should call this function twice for everypixel. Did you compare the performance ? maybe we should use `inline`?

**Comment by penww** [comment]
@ahcorde Thanks for your suggestion. I ignored the performance impact of function calls, will change it to `inline`.

I will continuelly work on `ImageDisplay` to support more YUV format, such as `nv12`, `nv24` etc.

BTW, eventhough it is inline, convert color for every pixel is not efficient, especially when image is large. 
Can we consider to convert with OpenGL / OpenMP? I can have a try on it.

**Comment by penww** [comment]
Has pushed new patch to change this function to `inline`.

- I also compared `std::clamp` with `((i & 0xFFFFFF00) == 0) ? i : (i < 0) ? 0 : 0xFF`, it shows `std::clamp` faster.
- And checked `std::tie`, it shows no more extra performance cost. 

In `O2` compile option, `std::clamp` and `std::tie` are faster than old code. I think compiler making optimization for `std` functions.

**Comment by zycczy** [comment]
Hi @ahcorde 
Is there any update for this PR

**Comment by ahcorde** [comment]
Pulls: ros2/rviz#1271
Gist: https://gist.githubusercontent.com/ahcorde/3e98ba46a6470006da49fd65022f8c58/raw/02f480667308172745d5283f9da22dc37754cf03/ros2.repos
BUILD args:   --packages-above-and-dependencies rviz_default_plugins --packages-above-and-dependencies rviz_default_plugins
TEST args:  --packages-above rviz_default_plugins --packages-above rviz_default_plugins
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14700
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21990/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16253/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1502/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22722/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to merge with `rolling` ?

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21996/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16257/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1507/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22729/)

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
