### PR TITLE
Update window close icon

### PR DESCRIPTION
**Pull request by rebecca-butler**
As discussed in #731, this PR replaces the `window_close` icon with the `failed_display` icon, which I also renamed to be more generic.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by rebecca-butler** [comment]
CI build : `--packages-up-to rviz_common`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14923/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9665/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12595/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15082/)

**Review by clalancette — APPROVED** [review]
Looks good with green CI.

**Review by jacobperron — APPROVED** [review]

**Comment by rebecca-butler** [comment]
Windows CI again:
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/15090/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-9-16/22372/1

**Pull request merged**
